//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioAppEscritorio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NjI0MTIyQDMyMzAyZTMxMmUzME0zdGJYSmZlVVBkOWgrYTBPUmtrOG95TTZrL3p5a1lVQ2dldktqTjV1O" +
            "EU9")]
        public string KeySynfusion {
            get {
                return ((string)(this["KeySynfusion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://biblioapp.eastus.cloudapp.azure.com:8081/biblioapp/v1/")]
        public string BaseURL {
            get {
                return ((string)(this["BaseURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string DatoAdmin {
            get {
                return ((string)(this["DatoAdmin"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8081/biblioapp/v1/")]
        public string UrlLocal {
            get {
                return ((string)(this["UrlLocal"]));
            }
            set {
                this["UrlLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=juegopeliculas1;AccountKey=RfGQdJH06PG" +
            "mviqzFSEmcfPOmId84hS6hqnsdHFywXNRxy7zG05nL9mKWewYsaF1JI/8z+UzAhCkfimv6jBcRg==;En" +
            "dpointSuffix=core.windows.net")]
        public string CadenaConexion {
            get {
                return ((string)(this["CadenaConexion"]));
            }
            set {
                this["CadenaConexion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imagenes")]
        public string NombreContenedorBlobs {
            get {
                return ((string)(this["NombreContenedorBlobs"]));
            }
            set {
                this["NombreContenedorBlobs"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("biblioapp22@gmail.com")]
        public string Correo {
            get {
                return ((string)(this["Correo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+34 000000000")]
        public string Telefono {
            get {
                return ((string)(this["Telefono"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nota 1")]
        public string NotasBlock {
            get {
                return ((string)(this["NotasBlock"]));
            }
            set {
                this["NotasBlock"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\BiblioAppEscritorio\\InstaladorBiblioAppEscritorio\\BiblioAp" +
            "p.chm")]
        public string RutaManual {
            get {
                return ((string)(this["RutaManual"]));
            }
        }
    }
}
